import operator
from typing import Dict, List, Annotated, TypedDict
from langchain_core.messages import BaseMessage


class GraphState(TypedDict):
    """
    GraphState is a TypedDict that represents the state of a graph-based AI assistant.

    Attributes:
        messages (List[BaseMessage]): A list of messages exchanged during the interaction, 
            annotated with an operator for combining them.
        queries (List[str]): A list of query strings submitted by the user.
        hits (List[Dict]): A list of dictionaries representing search results or hits 
            corresponding to the queries.
        round_idx (int): The current round index in the interaction.
        max_rounds (int): The maximum number of interaction rounds allowed.
        max_results_per_query (int): The maximum number of results to return for each query.
        answer (str): The final answer or response generated by the assistant.
        actions (List[str]): A list of actions performed during the interaction.
    """
    messages: Annotated[List[BaseMessage], operator.add]
    queries: List[str]
    hits: List[Dict]
    round_idx: int
    max_rounds: int
    max_results_per_query: int
    answer: str
    actions: List[str]